import 'package:hospital/consts/consts.dart';

class AppStrings {
  static String appname = "Careapp",
      bestDocapp = "Best Doctor\n Appointment App",
      welcomeBack = "Welcome back!",
      weAreExcited = "We are excited to have to you back!",
      signupNow =
          "Sign up now and start exploring all that our app has to offer.",
      email = "Email",
      emailHint = "Enter your email...",
      password = "Password",
      passwordHint = "Enter your password here...",
      fullname = "Full Name",
      fullnameHint = "Enter your name here...",
      confirmPassword = "Confirm Password",
      forgetPassword = "Forget Password ?",
      login = "Login",
      signup = "Sign Up",
      welcome = "Welcome",
      search = "Search Doctor",
      alreadyHaveAccount = "Already Have an account?",
      dontHaveAccount = "Don't have an account ?",
      category = "Speciality",
      doctor = "Doctor Login",
      settings = "Settings",
      body = "Body",
      ear = "Ear",
      eye = "Eye",
      heart = "Heart",
      kidney = "Kidney",
      liver = "Liver",
      lung = "Lungs",
      stomach = "Stomach",
      tooth = "Tooth",
      dantist = "Dantist",
      cardiologist = "Cardiologist",
      dermatologist = "Dermatologist",
      ayurvoda = "Ayurvoda",
      eyecare = "Eye Care",
      ortho = "Orthopedic",
      urologist = "Urologist",
      medicine = "Medicine",
      physiological = "Physiological",
      gynecologist = "Gynecologist",
      termsCondition = "Terms & Condition",
      signout = "Sign Out",
      changePassword = "Change Password";
}

var iconsList = [
  AppAssets.body,
  AppAssets.ear,
  AppAssets.eye,
  AppAssets.heart,
  AppAssets.kidney,
  AppAssets.liver,
  AppAssets.lung,
  AppAssets.stomach,
  AppAssets.tooth,
];

var iconsTitleList = [
  AppStrings.body,
  AppStrings.ear,
  AppStrings.eye,
  AppStrings.heart,
  AppStrings.kidney,
  AppStrings.liver,
  AppStrings.lung,
  AppStrings.stomach,
  AppStrings.tooth,
];
